# Generated by Django 3.1.7 on 2021-03-31 19:22

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_remove_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(
                blank=True, null=True,
                verbose_name='Дата и время созвона'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(
                blank=True,
                help_text='Необязательный комментарий к '
                          'заказу',
                verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[('NOCASH', 'Безналично'), ('CASH', 'Наличные')],
                default='NOCASH', max_length=6, verbose_name='способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now,
                null=True, verbose_name='Дата и время регистрации'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('UN', 'Необработанный'),
                         ('CA', 'Отмененный'),
                         ('AC', 'Принятый'),
                         ('PR', 'Приготовленный'),
                         ('SH', 'Отгруженный'),
                         ('CO', 'Выполненный')],
                default='UN', max_length=2, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='value',
            field=models.DecimalField(
                decimal_places=2, default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='стоимость'),
        ),
    ]
