# Generated by Django 3.1.7 on 2021-03-25 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_remove_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='стоимость'),
        ),
    ]
