# Generated by Django 3.1.7 on 2021-03-25 19:11

from django.db import migrations, models


def move_backward(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all():
        item.value = 0
        item.save()


def fill_values(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all():
        if item.value != 0:
            continue
        item.value = item.product.price * item.quantity
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_value'),
    ]

    operations = [
        migrations.RunPython(fill_values, move_backward),
    ]
