# Generated by Django 3.1.7 on 2021-04-03 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0041_0040_orderitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='дата и время созвона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True,
                                       verbose_name='дата и время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registrated_at',
            field=models.DateTimeField(blank=True,
                                       default=django.utils.timezone.now,
                                       null=True, verbose_name='дата и время '
                                                               'регистрации'),
        ),
    ]
