# Generated by Django 3.1.7 on 2021-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20210325_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UN', 'Необработанный'), ('CA', 'Отмененный'), ('AC', 'Принятый'), ('PR', 'Приготовленный'), ('SH', 'Отгруженный'), ('CO', 'Выполненный')], default='UN', max_length=2, verbose_name='статус'),
        ),
    ]
