# Generated by Django 3.1.7 on 2021-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Необязательный комментарий к заказу', verbose_name='комментарий'),
        ),
    ]
