# Generated by Django 3.1.7 on 2021-04-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0042_auto_20210403_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressPoint',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True, serialize=False,
                                  verbose_name='ID')),
                ('address',
                 models.CharField(max_length=500, verbose_name='адрес')),
                ('latitude',
                 models.DecimalField(
                     blank=True, decimal_places=6, max_digits=9,
                     null=True, verbose_name='широта')),
                ('longitude',
                 models.DecimalField(
                     blank=True, decimal_places=6, max_digits=9,
                     null=True, verbose_name='долгота')),
            ],
        ),
    ]
