# Generated by Django 3.1.7 on 2021-04-04 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0043_addresspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresspoint',
            name='query_at',
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now, null=True,
                verbose_name='дата и время регистрации'),
        ),
        migrations.AlterField(
            model_name='addresspoint',
            name='address',
            field=models.CharField(db_index=True,
                                   max_length=500,
                                   unique=True,
                                   verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True,
                                   max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True,
                                   max_length=50, verbose_name='название'),
        ),
    ]
