# Generated by Django 3.2.5 on 2021-07-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20210404_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresspoint',
            old_name='query_at',
            new_name='registered_at',
        ),
    ]
